name: cloudflare-deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudflare-deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn build
      - run: yarn deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
